# permissions for end users to edit clusterissuers.
apiVersion: rbac.yaml.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-editor-role
rules:
- apiGroups:
  - cert.dana.io
  resources:
  - clusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert.dana.io
  resources:
  - clusterissuers/status
  verbs:
  - get
