# permissions for end users to view issuers.
apiVersion: rbac.yaml.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: issuer-viewer-role
rules:
- apiGroups:
  - cert.dana.io
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert.dana.io
  resources:
  - issuers/status
  verbs:
  - get
