apiVersion: cert.dana.io/v1alpha1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: cert-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-sample
spec:
  apiEndpoint: "https://test.com"
  authSecretName: "cert-secret"
  waitTimeout: "5s"
  certificateRestrictions:
    privateKeyRestrictions:
      allowedPrivateKeyAlgorithms:
        - RSA
      allowedPrivateKeySizes:
        - 4096
    subjectRestrictions:
      allowedOrganizations:
        - dana.com
      allowedCountries:
        - il
      allowedOrganizationalUnits:
        - dana
      allowedProvinces:
        - test
      allowedStreetAddresses:
        - test
      allowedPostalCodes:
        - test
      allowedSerialNumbers:
        - test
    usageRestrictions:
      allowedUsages:
        - server auth
    domainRestrictions:
      allowedDomains:
        - dana.com
      allowedSubdomains:
        - test
    subjectAltNamesRestrictions:
      allowDNSNames: true
      allowIPAddresses: false
      allowAllowedURISANs: false
      allowAllowedEmailSANs: false