apiVersion: cert.dana.io/v1alpha1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: cert-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-sample
spec:
  apiEndpoint: "https://test.com"
  downloadEndpoint: "/download?test?test"
  authSecretName: "cert-secret"
  form: "chain"
  httpConfig:
    skipVerifyTLS: true
    waitTimeout: "5s"
    retryBackoff:
      duration: "5s"
      steps: 10
  certificateRestrictions:
    subjectAltNamesRestrictions:
      allowDNSNames: true
      allowIPAddresses: false
      allowAllowedURISANs: false
      allowAllowedEmailSANs: false